#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Search\Engine\Factory as EngineFactory;

$factory  = new EngineFactory();

$engine = $factory->makeEngine('solr', 'member.global_search');

$results = $engine
    ->query('Apple')
    ->page(1)
    ->itemsPerPage(5)
    ->search();

/* GS */ echo __FILE__.': '.__LINE__.'<pre>';print_r($results);echo'</pre>';exit;
